
# https://hub.docker.com/repository/docker/rardcode/chrony/tags

services:
  chrony:
    image: rardcode/chrony
    container_name: chrony
    #environment:
      #- ALLOW_CIDR=0.0.0.0/0 # clients to connect and get the time. Default is none.
      #- NTP_SERVER=time.inrimme.it # The NTP server to get the time to set from. Default is pool.ntp.org.
      #- SYNC_RTC=false # Sync the realtime clock on the machine/instance the service is running. Default is true.
    network_mode: host # Recommended so that clients come with the real ip, otherwise they would all get with only ip, that of the docker
    cap_add:
      - SYS_TIME
    restart: unless-stopped
